[package]
name = "tof-dataclasses"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
random=[]

[dependencies]
# logging
log = "0.4"
pretty_env_logger = "0.4"

# for testing
# used for the random number generation
rand = "0.8"


# strum to enhance enum 
# with messages, iterators
strum = "0.24"
strum_macros = "0.24"

#nom = "7.1"
