[package]
name = "tof-dataclasses"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
random=[]

[dependencies]
# logging
log = "0.4"
pretty_env_logger = "0.4"

# for testing
# used for the random number generation
rand = "0.8"
