[package]
name = "tof-dataclasses"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
random=[]

[dependencies]
# logging
log = "0.4"
pretty_env_logger = "0.4"

# for testing
# used for the random number generation
rand = "0.8"

# nom for cominatoric parsers
nom = "7.1"
# strum to enhance enum 
# with messages, iterators
strum = "0.24"
strum_macros = "0.24"

sqlite = "0.30"

