[package]
name = "liftof-lib"
version = "0.10.1"
edition = "2021"
rust-version = "1.78"

[features]
random   = []
debug    = []
database = ["tof-dataclasses/database"]
#[[lib]]
#name = "liftof-lib"
#path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#ndarray = "0.15"
#nlopt = "0.7"

#nalgebra = "0.32"
#nalgebra-linalg = "0.32"

[dependencies]

serde             = { workspace = true } 
serde_json        = { workspace = true } 
crossbeam-channel = { workspace = true } 
zmq               = { workspace = true }
log               = { workspace = true }
signal-hook       = { workspace = true }
# parse command line arguments
clap              = { workspace = true }

#ssh2              = "0.9"
toml              = "0.8"

tof-dataclasses = { path = "../../dataclasses/rust/tof-dataclasses" , features = ["tofcontrol","smoothed_z_score"], version = "0.10"} 


colored     = "2.0"
env_logger  = "0.10"

ureq        = "2.1"
indicatif   = "0.17"
#cfg-if      = "1.0" # TODO - have a propper debugging feature

#[target.armv7-unknown-linux-gnueabi]
#linker = "/usr/bin/arm-none-eabi-gcc"

