[package]
name = "liftof-tui"
version = "0.12.0"
edition = "2024"

[dependencies]
cfg-if            = { workspace = true }
zmq               = { workspace = true } 
log               = { workspace = true }
clap              = { workspace = true } 
serde             = { workspace = true }
serde_json        = { workspace = true } 
crossbeam-channel = { workspace = true }
chrono            = { version = "0.4", features = ["serde"] }
ndhistogram       = "0.10"

# tui stuff
crossterm  = { version = "0.28", features=["serde"]}
ratatui    = { version = "0.29", features = ["all-widgets"]}
tui-popup  = "0.6"
tui-logger = "0.14"

gondola-core = { workspace = true }

#backtrace-on-stack-overflow = "0.3"

