---
title: GAPS Master Data Pipeline Diagram
---
%%{
  init: {
    'flowchart': { 'curve': 'monotoneY' },
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#2B3467',
      'primaryTextColor': '#FCFFE7',
      'primaryBorderColor': '#BAD7E9',
      'lineColor': '#EB455F',
      'secondaryColor': '#006100',
      'tertiaryColor': '#BAD7E9'
    }
  }
}%%
flowchart TB
    LTB1-.->MasterTrigger
    MasterTrigger== "EventID" ==> Tracker
    MasterTrigger== "EventID,HitMask" ==>TofServer
    FlightComputer== "EventPayload" ==>GSE
    FlightComputer-- "Commands" -->FlightSystewms
    GSE-- "Commands" -->FlightComputer
    subgraph TOFSystem-RAT1
    Paddle1-.->LTB1
    Paddle2-.->LTB1
    Paddle3-.->LTB1
    Paddle4-.->LTB1
    Paddle5-.->LTB1
    Paddle6-.->LTB1
    Paddle7-.->LTB1
    Paddle8-.->LTB1
    Paddle1-.->RB1
    Paddle2-.->RB1
    Paddle3-.->RB1
    Paddle4-.->RB1
    Paddle5-.->RB2
    Paddle6-.->RB2
    Paddle7-.->RB2
    Paddle8-.->RB2
    LTB1-.->RB1
    LTB1-.->RB2
    RB1== "Events" ==>TofServer
    RB2== "Events" ==>TofServer
    TofServer-- "Commands" -->RB1
    TofServer-- "Commands" -->RB2
    subgraph TofComputer
    TofServer[[ServerProgram]]
    end
    end
    Tracker== "Events" ==>FlightComputer
    FlightComputer-- "Commands" -->Tracker
    GSE<==>UHCRA
    GSE==> SQlite[(SQLiteDB)]
    subgraph InflightStorage
    BinaryFile[(BinaryFile)]
    end
    TofServer== "TofEvents,Housekeeping" ==>FlightComputer
    FlightComputer-- "Commands" -->TofServer
    TofServer==>BinaryFile[(BinaryFile)]
    FlightComputer==>BinaryFile[(BinaryFile)]
    subgraph Ground
    GSE
    SQlite
    UHCRA
    end
  
