---
title: LIFTOF Readoutboard clients
---
%%{
  init: {
    'flowchart': { 'curve': 'monotoneY' },
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#2B3467',
      'primaryTextColor': '#FCFFE7',
      'primaryBorderColor': '#BAD7E9',
      'lineColor': '#EB455F',
      'secondaryColor': '#006100',
      'tertiaryColor': '#BAD7E9'
    }
  }
}%%
flowchart TB
  TofComputer -- TofCommand --> ControlThread
  subgraph "liftof-rb (RB/OS Level)"
  ControlThread
  EventCacheThread
  BufferWorker
  HeartBeatThread
  MonitoringThread
  RunThread
  OSMememoryDevUIO0
  end
  ControlThread -- TofResponse --> TofComputer
  ControlThread -- EventRequest --> EventCacheThread
  ControlThread -- MoniPacketRequest --> MonitoringThread
  ControlThread -- Start/Stop --> HeartBeatThread
  HeartBeatThread -- KeepAlive --> BufferWorker
  HeartBeatThread -- KeepAlive --> EventCacheThread
  HeartBeatThread -- KeepAlive --> MonitoringThread
  HeartBeatThread -- KeepAlive --> HeartBeatThread
  ControlThread -- RunStart/Stop --> RunThread
  HeartBeatThread == Heartbeat ==> TofComputer
  EventCacheThread == Event ==> TofComputer
  MonitoringThread == Moni  ==> TofComputer
  BufferWorker == Bytestream ==> EventCacheThread
  RunThread -- RunStart/Stop --> OSMememoryDevUIO0
  MonitoringThread -- RequestEnv --> OSMememoryDevUIO0
  BufferWorker -- SwitchBUff --> OSMememoryDevUIO0
  OSMememoryDevUIO0 <--> DRS4

