[package]
name        = "liftof-cc" # the name of the package
version     = "0.5.0"    # the current version, obeying semver
authors     = ["J.A. Stoessl <stoessl@hawaii.edu>", "Jeff Zweerink <zweering@astro.ucla.edu>"]
description = "A programm for the GAPS science instrument. Read out the time-of-flight detectors and process their data."

[[bin]]
name  = "liftof-cc"
#test  = false
#bench = false

[[bin]]
name = "mt-readout"
path = "src/bin/mt_readout.rs"

[features]
# diagnostics flag switch 
# on e.g. write waveforms to 
# hdf
diagnostics = []

# allows for the generation 
# of random data
random =[]

[dependencies]

tof-dataclasses = { path = "../../dataclasses/rust/tof-dataclasses" , features = ["random"], version = "0.5"} 
liftof-lib = { path = "../liftof-lib" , features = ["random"], version="0.5"}

zmq = "0.10.0"
# this is technically optional
# it is just used to integrate
# with the general cmake
cmake = "0.1.49"

# used only for diagnostics
#hdf5    = "0.8.1"
ndarray = "0.15"

# used for the random number generation
rand = "0.8"

# parse command line arguments
clap = { version = "4.0", features = ["derive"] }

# json de/serialization for config files

json = "0.12"

local-ip-address = "0.5"

# msmc channels
crossbeam-channel = "0.5"

ctrlc = "3.2"



# logging
log = "0.4"
pretty_env_logger = "0.4"
