data_dir = ""
calibration_dir = ""
runtime_sec = 0
packs_per_file = 0
fc_pub_address = ""
fc_sub_address = ""
mtb_address = "tcp://10.0.1.10:50001"
mtb_moni_interval_sec = 0
cpu_moni_interval_sec = 0
rb_ignorelist = []
evb_cachesize = 0
evb_n_mte_per_loop = 0
evb_n_rbe_per_loop = 0
evb_build_strategy = "Adaptive"
ana_int_start = 270.0
ana_int_window = 70.0
ana_ped_thresh = 10.0
ana_ped_begin_bin = 10
ana_ped_win_bins = 50
ana_use_zscore = false
ana_find_pks_t_start = 270.0
ana_find_pks_t_window = 70.0
ana_min_peak_size = 3
ana_find_pks_thresh = 10.0
ana_max_peaks = 5
ana_cfd_fraction = 0.20000000298023224
