[data]
no_waveform        = '/prestaging/no-waveforms'
waveform           = '/prestaging/waveforms'
campaign_moni_data = '/data2/gaps/L0/all-moni/'
tof_calib          = '/data1/gaps/mcmurdo/tof/calib'
allow_write        = true
[system]
ncpu               = 32 
