[data]
no_waveform        = '/prestaging/no-waveforms'
waveform           = '/prestaging/waveforms'
campaign_moni_data = '/prestaging/all-moni/'
tof_calib          = '/prestaging/tof-calib/'
allow_write        = true
[system]
ncpu               = 32 
