[project]
name = "gander"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Achim Stoessl", email = "achim.stoessl@gmail.com" }
]
dependencies = [
    "charmingbeauty>=0.1.4",
    "pydashi>=2.0.1",
    "matplotlib>=3.10.1",
    "hermes-py>=0.2.0",
    "streamlit>=1.45.0",
    "django>=5.2",
    "vtk>=9.4.2",
    "loguru>=0.7.3",
    "stqdm>=0.0.5",
    "scipy>=1.15.3",
    "polars>=1.31.0",
    "cmocean>=4.0.3",
    "tomli-w>=1.2.0",
    "pyvista>=0.46.3",
    "stpyvista>=0.1.4",
    "gondola @ file:///home/achim/gaps-online-software/gander/gondola-0.11.7-cp311-abi3-manylinux_2_39_x86_64.whl", 
]
    ##"gondola>=0.11.4",


readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.rye.scripts]
gander = "streamlit run gander.py --server.headless true --server.port 8080"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/gander"]
