var annotated_dup =
[
    [ "gondola", "namespacegondola.html", [
      [ "Cooling", "structgondola_1_1Cooling.html", "structgondola_1_1Cooling" ],
      [ "CRFrame", "structgondola_1_1CRFrame.html", "structgondola_1_1CRFrame" ],
      [ "CRFrameObject", "structgondola_1_1CRFrameObject.html", "structgondola_1_1CRFrameObject" ],
      [ "CRReader", "structgondola_1_1CRReader.html", "structgondola_1_1CRReader" ],
      [ "CRWriter", "structgondola_1_1CRWriter.html", "structgondola_1_1CRWriter" ],
      [ "IOError", "classgondola_1_1IOError.html", "classgondola_1_1IOError" ],
      [ "RBCalibration", "structgondola_1_1RBCalibration.html", "structgondola_1_1RBCalibration" ],
      [ "RBEvent", "structgondola_1_1RBEvent.html", "structgondola_1_1RBEvent" ],
      [ "RBEventHeader", "structgondola_1_1RBEventHeader.html", "structgondola_1_1RBEventHeader" ],
      [ "RBWaveform", "structgondola_1_1RBWaveform.html", "structgondola_1_1RBWaveform" ],
      [ "RecoHit", "structgondola_1_1RecoHit.html", "structgondola_1_1RecoHit" ],
      [ "TelemetryEvent", "structgondola_1_1TelemetryEvent.html", "structgondola_1_1TelemetryEvent" ],
      [ "TelemetryPacket", "structgondola_1_1TelemetryPacket.html", "structgondola_1_1TelemetryPacket" ],
      [ "TelemetryPacketHeader", "structgondola_1_1TelemetryPacketHeader.html", "structgondola_1_1TelemetryPacketHeader" ],
      [ "TelemetryPacketReader", "structgondola_1_1TelemetryPacketReader.html", "structgondola_1_1TelemetryPacketReader" ],
      [ "TofEvent", "structgondola_1_1TofEvent.html", "structgondola_1_1TofEvent" ],
      [ "TofEventSummary", "structgondola_1_1TofEventSummary.html", "structgondola_1_1TofEventSummary" ],
      [ "TofHit", "structgondola_1_1TofHit.html", "structgondola_1_1TofHit" ],
      [ "TofMetaData", "structgondola_1_1TofMetaData.html", "structgondola_1_1TofMetaData" ],
      [ "TofPacketReader", "classgondola_1_1TofPacketReader.html", "classgondola_1_1TofPacketReader" ],
      [ "TofPaddle", "structgondola_1_1TofPaddle.html", "structgondola_1_1TofPaddle" ],
      [ "TofPaddleTimingConstant", "structgondola_1_1TofPaddleTimingConstant.html", "structgondola_1_1TofPaddleTimingConstant" ],
      [ "TrackerStrip", "structgondola_1_1TrackerStrip.html", "structgondola_1_1TrackerStrip" ],
      [ "TrackerStripMask", "structgondola_1_1TrackerStripMask.html", "structgondola_1_1TrackerStripMask" ],
      [ "TrackerStripPedestal", "structgondola_1_1TrackerStripPedestal.html", "structgondola_1_1TrackerStripPedestal" ],
      [ "Tracklet", "structgondola_1_1Tracklet.html", "structgondola_1_1Tracklet" ],
      [ "TrkCalibratedHit", "structgondola_1_1TrkCalibratedHit.html", "structgondola_1_1TrkCalibratedHit" ],
      [ "TrkEvent", "structgondola_1_1TrkEvent.html", "structgondola_1_1TrkEvent" ],
      [ "TrkEventPacket", "structgondola_1_1TrkEventPacket.html", "structgondola_1_1TrkEventPacket" ],
      [ "TrkHeader", "structgondola_1_1TrkHeader.html", "structgondola_1_1TrkHeader" ],
      [ "TrkHit", "structgondola_1_1TrkHit.html", "structgondola_1_1TrkHit" ],
      [ "TrkMetaData", "structgondola_1_1TrkMetaData.html", "structgondola_1_1TrkMetaData" ]
    ] ],
    [ "std", null, [
      [ "formatter< gondola::EventStatus >", "structstd_1_1formatter_3_01gondola_1_1EventStatus_01_4.html", "structstd_1_1formatter_3_01gondola_1_1EventStatus_01_4" ]
    ] ],
    [ "CPUMoniData", "structCPUMoniData.html", "structCPUMoniData" ],
    [ "FromTofPacket", "structFromTofPacket.html", null ],
    [ "LTBMoniData", "structLTBMoniData.html", "structLTBMoniData" ],
    [ "MtbMoniData", "structMtbMoniData.html", "structMtbMoniData" ],
    [ "Option", "structOption.html", "structOption" ],
    [ "PAMoniData", "structPAMoniData.html", "structPAMoniData" ],
    [ "PBMoniData", "structPBMoniData.html", "structPBMoniData" ],
    [ "RBMoniData", "structRBMoniData.html", "structRBMoniData" ],
    [ "SimPrimary", "structSimPrimary.html", "structSimPrimary" ],
    [ "TofPacket", "structTofPacket.html", "structTofPacket" ]
];