var hierarchy =
[
    [ "gondola::Cooling", "structgondola_1_1Cooling.html", null ],
    [ "CPUMoniData", "structCPUMoniData.html", null ],
    [ "gondola::CRFrame", "structgondola_1_1CRFrame.html", null ],
    [ "gondola::CRFrameObject", "structgondola_1_1CRFrameObject.html", null ],
    [ "gondola::CRReader", "structgondola_1_1CRReader.html", null ],
    [ "gondola::CRWriter", "structgondola_1_1CRWriter.html", null ],
    [ "std::formatter", null, [
      [ "std::formatter< gondola::EventStatus >", "structstd_1_1formatter_3_01gondola_1_1EventStatus_01_4.html", null ],
      [ "std::formatter< gondola::HitQuality >", "structstd_1_1formatter_3_01gondola_1_1HitQuality_01_4.html", null ]
    ] ],
    [ "FromTofPacket< Derived >", "structFromTofPacket.html", null ],
    [ "FromTofPacket< MtbMoniData >", "structFromTofPacket.html", [
      [ "MtbMoniData", "structMtbMoniData.html", null ]
    ] ],
    [ "gondola::IOError", "classgondola_1_1IOError.html", null ],
    [ "LTBMoniData", "structLTBMoniData.html", null ],
    [ "std::optional", null, [
      [ "Option< String >", "structOption.html", null ],
      [ "Option< f32 >", "structOption.html", null ],
      [ "Option< T >", "structOption.html", null ]
    ] ],
    [ "PAMoniData", "structPAMoniData.html", null ],
    [ "PBMoniData", "structPBMoniData.html", null ],
    [ "gondola::RBCalibration", "structgondola_1_1RBCalibration.html", null ],
    [ "gondola::RBEvent", "structgondola_1_1RBEvent.html", null ],
    [ "gondola::RBEventHeader", "structgondola_1_1RBEventHeader.html", null ],
    [ "RBMoniData", "structRBMoniData.html", null ],
    [ "gondola::RBWaveform", "structgondola_1_1RBWaveform.html", null ],
    [ "gondola::RecoHit", "structgondola_1_1RecoHit.html", null ],
    [ "SimPrimary", "structSimPrimary.html", null ],
    [ "gondola::TelemetryEvent", "structgondola_1_1TelemetryEvent.html", null ],
    [ "gondola::TelemetryPacket", "structgondola_1_1TelemetryPacket.html", null ],
    [ "gondola::TelemetryPacketHeader", "structgondola_1_1TelemetryPacketHeader.html", null ],
    [ "gondola::TelemetryPacketReader", "structgondola_1_1TelemetryPacketReader.html", null ],
    [ "gondola::TofEvent", "structgondola_1_1TofEvent.html", null ],
    [ "gondola::TofEventSummary", "structgondola_1_1TofEventSummary.html", null ],
    [ "gondola::TofHit", "structgondola_1_1TofHit.html", null ],
    [ "gondola::TofMetaData", "structgondola_1_1TofMetaData.html", null ],
    [ "TofPacket", "structTofPacket.html", null ],
    [ "gondola::TofPacketReader", "classgondola_1_1TofPacketReader.html", null ],
    [ "gondola::TofPaddle", "structgondola_1_1TofPaddle.html", null ],
    [ "gondola::TofPaddleTimingConstant", "structgondola_1_1TofPaddleTimingConstant.html", null ],
    [ "gondola::TrackerStrip", "structgondola_1_1TrackerStrip.html", null ],
    [ "gondola::TrackerStripMask", "structgondola_1_1TrackerStripMask.html", null ],
    [ "gondola::TrackerStripPedestal", "structgondola_1_1TrackerStripPedestal.html", null ],
    [ "gondola::Tracklet", "structgondola_1_1Tracklet.html", null ],
    [ "gondola::TrkCalibratedHit", "structgondola_1_1TrkCalibratedHit.html", null ],
    [ "gondola::TrkEvent", "structgondola_1_1TrkEvent.html", null ],
    [ "gondola::TrkEventPacket", "structgondola_1_1TrkEventPacket.html", null ],
    [ "gondola::TrkHeader", "structgondola_1_1TrkHeader.html", null ],
    [ "gondola::TrkHit", "structgondola_1_1TrkHit.html", null ],
    [ "gondola::TrkMetaData", "structgondola_1_1TrkMetaData.html", null ]
];