var hierarchy =
[
    [ "Gaps::Telemetry::Cooling", "structGaps_1_1Telemetry_1_1Cooling.html", null ],
    [ "CPUMoniData", "structCPUMoniData.html", null ],
    [ "gondola::CRFrame", "structgondola_1_1CRFrame.html", null ],
    [ "gondola::CRFrameObject", "structgondola_1_1CRFrameObject.html", null ],
    [ "gondola::CRReader", "structgondola_1_1CRReader.html", null ],
    [ "std::formatter", null, [
      [ "std::formatter< gondola::EventStatus >", "structstd_1_1formatter_3_01gondola_1_1EventStatus_01_4.html", null ]
    ] ],
    [ "FromTofPacket< Derived >", "structFromTofPacket.html", null ],
    [ "FromTofPacket< MtbMoniData >", "structFromTofPacket.html", [
      [ "MtbMoniData", "structMtbMoniData.html", null ]
    ] ],
    [ "Gaps::IOError", "classGaps_1_1IOError.html", null ],
    [ "LTBMoniData", "structLTBMoniData.html", null ],
    [ "gondola::MasterTriggerEvent", "structgondola_1_1MasterTriggerEvent.html", null ],
    [ "Gaps::Telemetry::MergedEvent", "structGaps_1_1Telemetry_1_1MergedEvent.html", null ],
    [ "Gaps::Telemetry::Packet", "structGaps_1_1Telemetry_1_1Packet.html", null ],
    [ "Gaps::Telemetry::PacketHeader", "structGaps_1_1Telemetry_1_1PacketHeader.html", null ],
    [ "PAMoniData", "structPAMoniData.html", null ],
    [ "PBMoniData", "structPBMoniData.html", null ],
    [ "gondola::RBCalibration", "structgondola_1_1RBCalibration.html", null ],
    [ "gondola::RBEvent", "structgondola_1_1RBEvent.html", null ],
    [ "gondola::RBEventHeader", "structgondola_1_1RBEventHeader.html", null ],
    [ "RBMoniData", "structRBMoniData.html", null ],
    [ "gondola::RBWaveform", "structgondola_1_1RBWaveform.html", null ],
    [ "SimPrimary", "structSimPrimary.html", null ],
    [ "gondola::TelemetryPacketReader", "structgondola_1_1TelemetryPacketReader.html", null ],
    [ "gondola::TofEvent", "structgondola_1_1TofEvent.html", null ],
    [ "TofEventHeader", "structTofEventHeader.html", null ],
    [ "gondola::TofEventSummary", "structgondola_1_1TofEventSummary.html", null ],
    [ "gondola::TofHit", "structgondola_1_1TofHit.html", null ],
    [ "Gaps::Telemetry::TofMetaData", "structGaps_1_1Telemetry_1_1TofMetaData.html", null ],
    [ "TofPacket", "structTofPacket.html", null ],
    [ "Gaps::TofPacketReader", "classGaps_1_1TofPacketReader.html", null ],
    [ "Gaps::TofPaddle", "structGaps_1_1TofPaddle.html", null ],
    [ "Gaps::TrackerStrip", "structGaps_1_1TrackerStrip.html", null ],
    [ "Gaps::TrackerStripMask", "structGaps_1_1TrackerStripMask.html", null ],
    [ "Gaps::TrackerStripPedestal", "structGaps_1_1TrackerStripPedestal.html", null ],
    [ "Gaps::Telemetry::TrkCalibratedHit", "structGaps_1_1Telemetry_1_1TrkCalibratedHit.html", null ],
    [ "Gaps::Telemetry::TrkEvent", "structGaps_1_1Telemetry_1_1TrkEvent.html", null ],
    [ "Gaps::Telemetry::TrkEventPacket", "structGaps_1_1Telemetry_1_1TrkEventPacket.html", null ],
    [ "Gaps::Telemetry::TrkHeader", "structGaps_1_1Telemetry_1_1TrkHeader.html", null ],
    [ "Gaps::Telemetry::TrkHit", "structGaps_1_1Telemetry_1_1TrkHit.html", null ],
    [ "Gaps::Telemetry::TrkMetaData", "structGaps_1_1Telemetry_1_1TrkMetaData.html", null ]
];