[package]
name    = "liftof-rb"
version = "0.11.0"
edition = "2024"
description = "Readoutboard data acquisition code for the TOF of the GAPS science experiment"

[[bin]]
name = "liftof-rb"
path = "src/main.rs"

[features]
database = ["gondola-core/database"]

[dependencies]
# addess raw memeory, e.g. /dev/uio0
memmap = "0.7"

crossbeam-channel = { workspace = true } 
log               = { workspace = true } 
clap              = { workspace = true } 
serde_json        = { workspace = true } 
zmq               = { workspace = true }
cfg-if            = { workspace = true }
gondola-core      = { workspace = true } 
#gondola-core = { path = "../../dataclasses/rust/tof-dataclasses" , features = ["tofcontrol","smoothed_z_score"], version = "0.10"} 

colored = "2.0"
env_logger = "0.10"

indicatif = ">=0.17.3"
signal-hook = "0.3"

[dependencies.tof-control]
version  = "0.9"
optional = false
git      = "https://github.com/GAPS-Collab/tof-control.git"
branch   = "minimal"
#[target.armv7-unknown-linux-gnueabi]
#linker = "/usr/bin/arm-none-eabi-gcc"
