[package]
name        = "liftof-cc" # the name of the package
version     = "0.11.3"    # the current version, obeying semver
authors     = ["J.A. Stoessl <stoessl@hawaii.edu>", "G. Tytus <gtytus@hawaii.edu>"]
description = "A programm for the GAPS science instrument. Read out the time-of-flight detectors and process their data."
edition     = "2024"
[[bin]]
name  = "liftof-cc"
#test  = false
#bench = false

[[bin]]
name = "liftof-scheduler"
path = "src/bin/liftof_scheduler.rs"

[features]
debug = []
tof-ctrl = ["gondola-core/tofcontrol", "tof-control"]
database = ["gondola-core/database"]


[dependencies]

clap              = { workspace = true }  
zmq               = { workspace = true }  
serde             = { workspace = true }  
serde_json        = { workspace = true }  
crossbeam-channel = { workspace = true }  
log               = { workspace = true }  
cfg-if            = { workspace = true }
signal-hook       = { workspace = true }
#chrono            = { worksapce = true }
gondola-core      = { workspace = true } 

chrono 		      = { version="0.4", features =["serde"]}


indicatif   = "0.17"
spinners    = "4.1.1"
# tof-control depends on comfy-table as well
comfy-table = { version = "7.1", default-features = false }
toml        = "0.8"
env_logger  = "0.10"

[dependencies.tof-control]
version  = "0.9.5"
rev      = "23ab243acf48c4c71a994964dee0b612b8cb6132"
#branch   = "minimal"
optional = true
git      = "https://github.com/GAPS-Collab/tof-control.git"
#rev      = "5f63d530fd293cdceede6383ac5b644bbe3deb30"

#[workspace.metadata.cross.target.x86_64-unknown-linux-musl]
## Install libssl-dev:arm64, see <https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#adding-dependencies-to-existing-images>
#pre-build = [
#    "dpkg --add-architecture $CROSS_DEB_ARCH", 
#    "apt-get update && apt-get --assume-yes install libsqlite3-dev:$CROSS_DEB_ARCH"
#]

