[package]
name = "liftof-rb"
version = "0.4.0"
edition = "2021"


#[[bin]]
#name = "watch-buffer-fill"
#path = "src/bin/watch_buffer_fill.rs"

[[bin]]
name = "liftof-rb"
path = "src/main.rs"

[[bin]]
name = "watch-buffer-fill"
path = "src/bin/watch_buffer_fill.rs"

[[bin]]
name = "scan-uio-buffers"
path = "src/bin/scan_uio_buffers.rs"

[[bin]]
name = "debug-idle"
path = "src/bin/debug_idle.rs"


[[bin]]
name = "debug-registers"
path = "src/bin/debug_registers.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liftof-lib = { path = "../liftof-lib"} 

# addess raw memeory, e.g. /dev/uio0
memmap = "0.7"

# multi-producer/multi-consumer channels
crossbeam-channel = "0.5"

tof-dataclasses = { path = "../../dataclasses/rust/tof-dataclasses" , features = ["random"]} 

zmq = "0.10.0"

log = "0.4"
pretty_env_logger = "0.4"

local-ip-address = "0.5"
clap = { version = "4.0", features = ["derive"] }

indicatif = ">=0.17.3"

libc = "0.2"
signal-hook = "0.3"

#[target.armv7-unknown-linux-gnueabi]
#linker = "/usr/bin/arm-none-eabi-gcc"
