[package]
name = "liftof-tui"
version = "0.10.0"
edition = "2021"


[dependencies]

serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
rand = { version = "0.7.3", default-features = false, features = ["std"] }
#tui = { version = "0.19", default-features = false, features = ['crossterm', 'serde'] }
#thiserror = "1.0"

tui-logger = { version = "0.11" } 
ratatui = { version = "0.26", features = ["all-widgets"]}

crossterm = { version = "0.23", features=["serde"]}
#tokio = { version = "1", features = ["full"] }

#eyre = "0.6"
#sysinfo = "0.27"

# multi-producer/multi-consumer channels
#crossbeam = "0.8"
crossbeam-channel = "0.5"

tof-dataclasses = { path = "../../dataclasses/rust/tof-dataclasses" , features = ["random", "database"], version = "0.9"}
liftof-lib = { path = "../liftof-lib" , features = ["random"], version = "0.9"}

# this is the "one and only" histogram 
# crate in my opinion
ndhistogram = "0.9.0"
zmq = "0.10.0"

log = "0.4"
clap = { version = "4.0", features = ["derive"] }

#num-traits = "0.2"

#[target.armv7-unknown-linux-gnueabi]
