[package]
name = "liftof-tui"
version = "0.10.2"
edition = "2021"

[features]
telemetry  = ["telemetry-dataclasses"]
default    = ["telemetry"]

[dependencies]

cfg-if     = { workspace = true }

zmq        = { workspace = true } 
log        = { worksapce = true }
clap       = { workspace = true } 
serde      = { worksapce = true }
serde_json = { workspace = true } 
crossbeam-channel = { workspace = true }

chrono     = { version = "0.4", features = ["serde"] }

# tui stuff
tui-logger = { version = "0.11" } 
ratatui    = { version = "0.26", features = ["all-widgets"]}
crossterm  = { version = "0.23", features=["serde"]}

#tokio = { version = "1", features = ["full"] }
#eyre = "0.6"
#sysinfo = "0.27"


tof-dataclasses = { workspace = true }
liftof-lib      = { path = "../liftof-lib" , features = ["random"], version = "0.10"}
telemetry-dataclasses = { path = "../../../telemetry/dataclasses/rust/telemetry-dataclasses", optional = true }

tui-popup = "0.3"

# this is the "one and only" histogram 
# crate in my opinion
ndhistogram = "0.9.0"

#num-traits = "0.2"

#[target.armv7-unknown-linux-gnueabi]
