[project]
name = "analysis"
version = "0.1.0"
description = "Various (personal) analysis code which leverages the code in this repository"
authors = [
    { name = "Achim Stoessl", email = "achim.stoessl@gmail.com" }
]
dependencies = [
    "ipython>=8.27.0",
    "numpy>=2.1.1",
    "pydashi>=0.1.3",
    "hermes-py>=0.2.0",
    "matplotlib>=3.9.2",
    "django>=5.1.1",
    "polars>=1.6.0",
    "charmingbeauty>=0.1.4",
    "jupyter>=1.1.1",
    "pyfonts>=0.0.1",
    "jinja2>=3.1.4",
    "pdfkit>=1.0.0",
    "nbstripout>=0.7.1",
    "gondola @ file:///srv/gaps/gaps-online-software/gondola-core/rust/gondola-core/target/wheels/gondola-0.11.0-cp311-abi3-manylinux_2_34_x86_64.whl"
]
readme = "README.md"
requires-python = ">= 3.11"

[tool.rye.scripts]
jupy-lab = "jupyter lab --port 9876"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/analysis"]
