name: BuildBot

on:
  workflow_dispatch:
  push:
    branches:
    - LELEWAA-0.10
    - PAKII-0.11
    - main
  pull_request:
    branches: 
    - LELEWAA-0.10
    - PAKII-0.11
    - main
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: 'true'
        show-progress: 'true'
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Get Version
      id: sw_version
      run: |
          # The shell automatically converts ${{ github.ref_name }} to a string.
          BRANCH_NAME="${{ github.ref_name }}"
          GOS_VERSION=$(echo "$BRANCH_NAME" | cut -d'-' -f2-)
          echo "version=$GOS_VERSION" >> $GITHUB_OUTPUT


    #- name: Set up GCC
    #  uses: egor-tensin/setup-gcc@v1
    #  with:
    #    version: 13
    #    platform: x64   

    - name: Set up rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true
        version: 'latest' 

    - name: Set up sphinx for python docs 
      run : cd ${{github.workspace}}/python/doc && rye sync

    - name: Install dependencies
      run : sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install -y cmake doxygen pybind11-dev graphviz lm-sensors libsqlite3-dev rsync
    
    - name: intall rust 
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && export PATH=$PATH:~/.cargo/bin

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: source $HOME/.cargo/env && cmake -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_LIFTOF=ON -DBUILD_CXXPYBINDINGS=ON -DBUILD_RUSTPYBINDINGS=ON -DBUILD_CXXDB=ON -DBUILD_CXXBINDINGS=ON -DBUILD_RUSTTELEMETRY=ON -DBUILD_CARASPACE=ON -DBUILD_EXAMPLES=ON

    - name: Build
      # Build your program with the given configuration
      #run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      run: source $HOME/.cargo/env && cd ${{github.workspace}}/build && make -j 4 
    
    - name: C++ Docs 
      run: source $HOME/.cargo/env && cd ${{github.workspace}}/build && make doc 

    - name: Install 
      run: source $HOME/.cargo/env && cd ${{github.workspace}}/build && make install
 
    - name: Test-Dataclasses
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #run: ctest -C ${{env.BUILD_TYPE}}
      run: source $HOME/.cargo/env && cd ${{github.workspace}}/tof/dataclasses/rust/tof-dataclasses && cargo test --features="random" && cargo test --all-features
    
    - name: Test-LiftofLib
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #run: ctest -C ${{env.BUILD_TYPE}}
      run: source $HOME/.cargo/env && cd ${{github.workspace}}/tof/liftof/liftof-lib && cargo test --all-features && cargo test 

    - name: Rust Docs
      run: source $HOME/.cargo/env && cd ${{github.workspace}}/build && make doc && make liftof-doc && make go-pybindings-rust-doc
    
    - name: Create .nojekyll
      run: touch ${{ github.workspace }}/build/doc/apidocs-v${{ steps.sw_version.outputs.version }}/html/.nojekyll
      shell: bash

    - name: Create python API docs
      run: source ${{github.workspace }}/install/setup-env.sh && cd ${{ github.workspace }}/python/doc/ && rye run sphinx-build -M html . build

    - name: Consolidate docs
      run: cp -r ${{ github.workspace }}/tof/liftof/target/doc/* ${{ github.workspace }}/build/doc/apidocs-v${{ steps.sw_version.outputs.version }}/html/
      shell: bash
    
    - name: Consolidate docs for pybindings 
      run: cp -r ${{ github.workspace }}/python/pybindings/target/doc/* ${{ github.workspace }}/build/doc/apidocs-v${{ steps.sw_version.outputs.version }}/html/
      shell: bash
      
    - name: Consolidate pydocs
      run: cp -r ${{ github.workspace }}/python/doc/build/html ${{ github.workspace }}/build/doc/apidocs-v${{ steps.sw_version.outputs.version }}/html/gaps_online
      shell: bash

    - name: Resort docs 
      run: mv ${{ github.workspace }}/build/doc/apidocs-v${{ steps.sw_version.outputs.version}}/html/* ${{ github.workspace }}/build/doc/apidocs-v${{ steps.sw_version.outputs.version }}/ 

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        #branch: ${{ inputs.branch }}
        #folder: ${{ github.workspace }}/build/doc/apidocs-v${{ steps.sw_version.outputs.version }}/html/
        folder: ${{ github.workspace }}/build/doc/
        branch: gh-pages

