name: PakiiBuildBot

on:
  workflow_dispatch:
  push:
    branches:
    - PAKII-0.11
  pull_request:
    branches: 
    - PAKII-0.11
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  pakii-build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: 'recursive'
        show-progress: 'true'
        token: ${{ secrets.PAT_TOKEN }}

    - name: Get Version
      id: sw_version
      run: |
          # The shell automatically converts ${{ github.ref_name }} to a string.
          BRANCH_NAME="${{ github.ref_name }}"
          GOS_VERSION=$(echo "$BRANCH_NAME" | cut -d'-' -f2-)
          echo "version=$GOS_VERSION" >> $GITHUB_OUTPUT

    #------------------------------------------------
    # dependencies setup 

    #- name: Set up GCC
    #  uses: egor-tensin/setup-gcc@v1
    #  with:
    #    version: 13
    #    platform: x64   

    - name: Set up rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true
        version: 'latest' 

    - name: Install dependencies
      run : sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install -y doxygen graphviz lm-sensors libsqlite3-dev rsync cmake 
    
    - name: intall rust 
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && export PATH=$PATH:~/.cargo/bin
    
    # ------------------------------------------------------
    # Documentation

    
    - name: Init cmake 
      run: cmake -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_CXX_BINDINGS=ON -DBUILD_CXX_DB=ON -DBUILD_CXX_EXAMPLES=ON -DBUILD_CXX_PYBINDINGS=OFF
    
    - name: C++ Docs 
      run: cd ${{github.workspace}}/build && make doc 
    
    # since liftof depends on gondola, this will automatically document gondola-core as 
    # well
    - name: Rust Docs 
      run: source $HOME/.cargo/env && cd ${{github.workspace}}/liftof && cargo doc --all-features 

    - name: Python Docs (gondola) 
      run: cd ${{ github.workspace }}/doc/python && rye lock --update-all && rye sync &&  rye run sphinx-build -M html . build 

    #- name: Gondola Docs
    #  run: source $HOME/.cargo/env && cd ${{github.workspace}}/gondola-core/rust/gondola-core && cargo doc --all-features 

    #---------------------------------
    # install/deploy docs 

    - name: Create .nojekyll
      run: touch ${{ github.workspace }}/build/doc/.nojekyll
      shell: bash
    
    - name: Create .nojekyll for api docs 
      run: touch ${{ github.workspace }}/build/doc/apidocs-v${{ steps.sw_version.outputs.version }}/.nojekyll
      shell: bash
    
    - name: Copy assets for docs 
      run: cp ${{ github.workspace }}/resources/assets/GAPSLOGO_2023_small.png ${{ github.workspace }}/build/doc/ 
      shell: bash

    # The C++ docs are already in the correct folder
    - name: Consolidate Rust docs
      run: cp -r ${{ github.workspace }}/liftof/target/doc/* ${{ github.workspace }}/build/doc/apidocs-v${{ steps.sw_version.outputs.version }}/
      shell: bash
    
    - name: Consolidate Python docs
      run: cp -r ${{ github.workspace }}/doc/python/build/html/* ${{ github.workspace }}/build/doc/apidocs-v${{ steps.sw_version.outputs.version }}/
      shell: bash
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        #branch: ${{ inputs.branch }}
        folder: ${{ github.workspace }}/build/doc/
        branch: gh-pages
        clean: false
    #--------------------------------------------
    # Compiling and testing 

    - name: Build CXX
      # Build your program with the given configuration
      #run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      run: cd ${{github.workspace}}/build && make -j 4 
    
    - name: Install C++ 
      run: cd ${{github.workspace}}/build && make install
    
    - name: Compile gondola-core Rust
      working-directory: gondola-core/rust/gondola-core 
      run: source $HOME/.cargo/env && cargo check --all-features 

    - name: Test-gondola-core Rust 
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #run: ctest -C ${{env.BUILD_TYPE}}
      run: source $HOME/.cargo/env && cd ${{github.workspace}}/gondola-core/rust/gondola-core && cargo test --features="random,database,advanced-algorithms,tof-liftof" 
    
    - name: Test Liftof-cc 
      working-directory: ${{github.workspace}}/liftof/liftof-cc
      run: source $HOME/.cargo/env && cargo test --all-features 

    - name: Test Liftof-rb
      working-directory: ${{github.workspace}}/liftof/liftof-rb 
      run: source $HOME/.cargo/env && cargo test --all-features   
